import { Inter, Work_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { Toaster } from 'react-hot-toast';


const inter = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <ClerkProvider>
    <html lang="en">
      {/* <GoogleOneTap /> */}
      <body className={inter.className}>
          {children}
          {/* Move components here to ensure they only render on the client */}
          <Toaster position="bottom-right" />
          {/* <GoogleOneTap /> Uncomment this if you need to use it */}
        </body>
    </html>
    </ClerkProvider>
  );
}
 